### ISSUE TITLE
Mining centralization over 90% in hands of 4 groups

### ISSUE THREAD

**Issue by SpiryMedia** [zenprotocol/zenprotocol#1]
Please make public the GPU miner to investors. We have spent 40.000.000$ on this project to be secured, not to be looted by a small group of people that have mined ZEN Protocol for the last 4 days without shame. 

This is an urgent matter as it risks economical centralization of early groups into centralized big pools. Already investors lost 4.000.000$ in the hands of these thieves.

**Comment by A-Manning** [comment]
Several GPU miners are publicly available now.
Please see the [mining docs](https://docs.zenprotocol.com/gpu-mining) for more info.

Closing.
